### ISSUE TITLE
Enchancement of counter example

### ISSUE THREAD

**Issue by lakshyabatman** [Ninja-Developers/kladi#13]
**Is your feature request related to a problem? Please describe.**
The current Counter example is very basic, so the idea to build a better application which showcases the project properly.

**Describe the solution you'd like**
The approach is to add the following details in the examples:
- Using styling to make sure example looks great.
- Using comments to describe the proper usage.
- Adding relevant links to the project, so the user can straight dive in the docs.

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by lakshyabatman** [comment]
Reference to #11

**Comment by Souvikns** [comment]
@lakshyabatman you may proceed.

**Comment by Souvikns** [comment]
@lakshyabatman **reminder** I have changed the file structure a bit before you start working pls pull the new changes.

**Comment by lakshyabatman** [comment]
Sure.

**Comment by lakshyabatman** [comment]
#14 solved this.
