### ISSUE TITLE
useState name clasing with react naming convention. 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/kladi#16]
## **Describe the bug**
Currently, the hook name clashes with the react naming convention. I think we should change it from `useState` to `useGlobalState` 

> Open to suggestion

**Comment by lakshyabatman** [comment]
Yes, but instead of it we can use ` useStoreState ` this naming convention describe better.

**Comment by Souvikns** [comment]
we can go with it but kladi is creating a global state, so I thought of going with it.

**Comment by lakshyabatman** [comment]
Yeah you're right?  Assign me this task, I'll send a PR asap.

**Comment by Souvikns** [comment]
@lakshyabatman you are assigned
