### ISSUE TITLE
[BUG] Badges are breaking in deployed GH Pages

### ISSUE THREAD

**Issue by vinitshahdeo** [Ninja-Developers/kladi#6]
Using markdown with html breaks in deployed Jekyll websites. To fix, either use HTML or convert to Markdown. Having markdown syntax between `<p></p>` tag renders it as text.

![Screenshot 2020-08-31 at 2 55 47 AM](https://user-images.githubusercontent.com/20594326/91669832-c2aaf800-eb35-11ea-9d21-70e7ad883fc0.png)
 
Check [this](https://ninja-developers.github.io/kladi/).

**Comment by vinitshahdeo** [comment]
![Screenshot 2020-08-31 at 3 04 45 AM](https://user-images.githubusercontent.com/20594326/91669964-c2f7c300-eb36-11ea-9654-aeb6fcf484d2.png)

@imabp This badge is 404ing.

**Comment by imabp** [comment]
Thankyou @vinitshahdeo 😁😁😁😁😁. Its Resolved.
![image](https://user-images.githubusercontent.com/53480076/91669981-f8041580-eb36-11ea-8664-b7709b213f66.png)

**Comment by vinitshahdeo** [comment]
![Screenshot 2020-08-31 at 3 06 43 AM](https://user-images.githubusercontent.com/20594326/91669991-07835e80-eb37-11ea-949e-51db1661d786.png)

@imabp NPM badge is breaking in `master` branch. Check once.

**Comment by imabp** [comment]
@vinitshahdeo Resolved. Hifive 😁😁😁
